POST https://javatodolist.herokuapp.com/TodoList
Content-Type: application/x-www-form-urlencoded

task=melon

###
POST https://javatodolist.herokuapp.com/TodoList
Content-Type: application/x-www-form-urlencoded

task=sandia

###
GET https://javatodolist.herokuapp.com/TodoList
Accept: application/json

###



